language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

before_script:
  - rustup toolchain add nightly || travis_terminate 1
  - rustup component add rustfmt --toolchain nightly || travis_terminate 1

script:
    - cargo +nightly fmt --all -- --check || travis_terminate 1
    - cargo build --verbose --all || travis_terminate 1
    - cargo test --verbose --all || travis_terminate 1
