language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  global:
    - RUST_BACKTRACE=1

matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly

script:
    - cargo fmt --all -- --check
    - cargo build --verbose --all
    - cargo test --verbose --all
