language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
env:
  global:
    RUST_BACKTRACE=1
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  script:
    - cargo build --verbose --all
    - cargo test --verbose --all
